Xsismart/Xsismart/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xsismart.Models;
using Xsismart.ViewModels;

namespace Xsismart.Controllers
{
    public class TransactionController : Controller
    {
        private readonly Xsismartcontext _context;

        public TransactionController(Xsismartcontext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> AddCart(VMTransactions trx)
        {
            try
            {
                OrderHeader header = new OrderHeader();
                OrderDetail detail = new OrderDetail();
                DateTime dt = DateTime.Now;
                int d = dt.Day;
                int m = dt.Month;
                int y = dt.Year;
                string CodeTrx = $"XM-{d}{m}{y}-0001";
                string LastCode = await LastCodeTransaction();

                if (LastCode != "")
                {
                    string lastString = LastCode.Substring(LastCode.Length - 4, 4);
                    int lastInt = Convert.ToInt32(lastString) + 1;
                    string joinString = "0000" + lastInt.ToString();
                    CodeTrx = $"XM-{d}-{m}-{y}-" + joinString.Substring(joinString.Length - 4, 4);
                }
                header = await _context.OrderHeaders.Where(a => a.IdCustomer == 1 && a.IsCheckout == false).FirstOrDefaultAsync();

                if (header == null)
                {
                    header = new OrderHeader();
                    header.CodeTransaction = CodeTrx;
                    //  header.IdCustomer = trx.IdCustomer;
                    header.IsCheckout = false;
                    header.IdCustomer = 1;
                    _context.Add(header);
                    await _context.SaveChangesAsync();
                }

                detail.IdProduct = trx.IdProduct;
                detail.IdHeader = header.IdHeader;
                detail.Quantity = trx.Quantity;
                detail.Amount = trx.Amount;
                _context.Add(detail);
                await _context.SaveChangesAsync();

                return Json(new { status = "success" });
            }
            catch (Exception e)
            {
                return Json(new { status = "error", message = e.Message.ToString() });
            }
        }

        public async Task<string> LastCodeTransaction()
        {
            string lastNoTrx = "";
            OrderHeader data = await _context.OrderHeaders.
                                     OrderByDescending(a => a.CodeTransaction).FirstOrDefaultAsync();
            if (data != null)
            {
                lastNoTrx = data.CodeTransaction;
            }
            return lastNoTrx;
        }
        public async Task<IActionResult> Invoice()
        {
            int idCust = 1;
            List<VMTransactions> list = await DataTransaction(idCust);
            DateTime date = DateTime.Now;

            decimal subtotal = await dataSumOrder(idCust);
            string subtotal1 = string.Format("{0:0,0.00}", subtotal);
            double tax = ((double)5 / 100) * ((double)subtotal);
            ViewBag.DateNow = date;
            ViewBag.SubTotal = subtotal1;
            ViewBag.IdHeader = list.Select(a => a.IdHeader).FirstOrDefault();
            ViewBag.IdCustomer = list.Select(a => a.IdCustomer).FirstOrDefault();
            ViewBag.IsCheckout = list.Select(a => a.IsCheckout).FirstOrDefault();


            ViewBag.Tax = tax;
            ViewBag.Total = ((double)subtotal + tax);
            ViewBag.CodeTransaction = list.Select(a => a.CodeTransaction).FirstOrDefault();

            return View(list);
        }

        public async Task<decimal> dataSumOrder(int idCust)
        {
            decimal subtotal = 0;
            subtotal = await (from head in _context.OrderHeaders
                              join detail in _context.OrderDetails
                              on head.IdHeader equals detail.IdHeader
                              where head.IdCustomer == idCust && head.IsCheckout == false
                              select detail.Amount).SumAsync();
            return subtotal;
        }

        public async Task<List<VMTransactions>> DataTransaction(int IdCustomer)
        {
            List<VMTransactions> list = await (from head in _context.OrderHeaders
                                               join detail in _context.OrderDetails
                                               on head.IdHeader equals detail.IdHeader
                                               join prod in _context.Products
                                               on detail.IdProduct equals prod.IdProduct
                                               join vari in _context.Variants
                                               on prod.IdVariant equals vari.IdVariant
                                               join cate in _context.Categories
                                               on vari.IdCategory equals cate.IdCategory
                                               where head.IdCustomer == IdCustomer && head.IsCheckout == false
                                               select new VMTransactions
                                               {
                                                   IdProduct = prod.IdProduct,
                                                   NameProduct = prod.NameProduct,
                                                   Price = prod.Price,
                                                   IdCustomer = head.IdCustomer,
                                                   IsCheckout = head.IsCheckout,
                                                   IdDetail = detail.IdDetail,
                                                   NameCategory = cate.NameCategory,
                                                   IdCategory = cate.IdCategory,
                                                   NameVariant = vari.NameVariant,
                                                   IdHeader = head.IdHeader,
                                                   CodeTransaction = head.CodeTransaction,
                                                   Amount = detail.Amount,
                                                   Quantity = detail.Quantity
                                               }).ToListAsync();

            return list;
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            VMTransactions orderDetail = await DataTrans(id);
            if (orderDetail == null)
            {
                return NotFound();
            }

            return View(orderDetail);
        }

        // POST: OrderDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(OrderDetail _detail)
        {
            if (ModelState.IsValid)
            {
                _context.Remove(_detail);
                await _context.SaveChangesAsync();
                return RedirectToAction("Invoice");
            }
            return View(_detail);
        }

     
        public async Task<VMTransactions> DataTrans(int id)
        {
            VMTransactions list = await (from head in _context.OrderHeaders
                                               join detail in _context.OrderDetails
                                               on head.IdHeader equals detail.IdHeader
                                               join prod in _context.Products
                                               on detail.IdProduct equals prod.IdProduct
                                               join vari in _context.Variants
                                               on prod.IdVariant equals vari.IdVariant
                                               join cate in _context.Categories
                                               on vari.IdCategory equals cate.IdCategory
                                               where detail.IdDetail == id && head.IsCheckout == false
                                               select new VMTransactions
                                               {
                                                   IdProduct = prod.IdProduct,
                                                   NameProduct = prod.NameProduct,
                                                   Price = prod.Price,

                                                   IdDetail = detail.IdDetail,
                                                   NameCategory = cate.NameCategory,
                                                   IdCategory = cate.IdCategory,
                                                   NameVariant = vari.NameVariant,
                                                   IdHeader = head.IdHeader,
                                                   CodeTransaction = head.CodeTransaction,
                                                   Amount = detail.Amount,
                                                   Quantity = detail.Quantity
                                               }).FirstOrDefaultAsync();
            return list;

        }

        [HttpPost]
        public async Task<IActionResult> Checkout(VMTransactions trx)
        {
         
            List<OrderDetail> detail = await DataOrder(trx.IdHeader);

            OrderHeader header = await _context.OrderHeaders.Where(a => a.IdCustomer == trx.IdCustomer && a.IdHeader == trx.IdHeader && a.IsCheckout == trx.IsCheckout).FirstOrDefaultAsync();
           
            try
            {
                header.IsCheckout = true;
                int counter = detail.Count();
                for (int i = 0; i < counter; i++)
                {
                    detail[i].IsDelete = true;

Xsismart/Xsismart/Views/Transaction/Delete.cshtml
@model Xsismart.ViewModels.VMTransactions

@{ ViewData["Title"] = "Delete";
                Layout = null; }



<div class="col-md-12">
    <!-- general form elements -->
    <div>
        <div class="card-header">
            <h5>Are you sure you want to delete this?</h5>
        </div>
        <div class="card-footer">
            <form asp-action="Delete" asp-controller="Transaction">
                <input type="hidden" asp-for="IdDetail" />
                <input type="submit" class="btn btn-block btn-outline-danger" value="Delete">
                <a asp-action="Invoice" class="btn btn-block btn-outline-info ">Back</a>
            </form>
        </div>
    </div>
</div>

Xsismart/Xsismart/Views/Transaction/Invoice.cshtml
@model IEnumerable<Xsismart.ViewModels.VMTransactions>
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Invoice</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="callout callout-info">
                    <h5><i class="fas fa-info"></i> Note:</h5>
                    This page has been enhanced for printing. Click the print button at the bottom of the invoice to test.
                </div>


                <!-- Main content -->
                <div class="invoice p-3 mb-3">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-12">
                            <h4>
                                <i class="fas fa-globe"></i> AdminLTE, Inc.
                                <small class="float-right">@ViewBag.DateNow</small>
                            </h4>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            From
                            <address>
                                <strong>Admin, Inc.</strong><br>
                                795 Folsom Ave, Suite 600<br>
                                San Francisco, CA 94107<br>
                                Phone: (804) 123-5432<br>
                                Email: info@almasaeedstudio.com
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            To
                            <address>
                                <strong>John Doe</strong><br>
                                795 Folsom Ave, Suite 600<br>
                                San Francisco, CA 94107<br>
                                Phone: (555) 539-1037<br>
                                Email: john.doe@example.com
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <b>Invoice #007612</b><br>
                            <br>
                            <b>Order ID:</b>@ViewBag.CodeTransaction<br>
                            <b>Payment Due:</b> 2/22/2014<br>
                            <b>Account:</b> @ViewBag.IdCustomer<br>
                            <b>IdHead:</b> @ViewBag.IdHeader<br>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                    <!-- Table row -->
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>

                                        <th>Product</th>
                                        <th>Name Variant</th>
                                        <th>Name Category</th>
                                        <th>Qty</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {

                                        <tr>
                                            <td>@item.NameProduct</td>
                                            <td>@item.NameVariant</td>
                                            <td>@item.NameCategory</td>
                                            <td>@item.Quantity</td>
                                            <td>@item.Price</td>
                                            <td>
                                                <a class="btn btn-danger btn-delete" id="IdDetail" data-id="@item.IdDetail">
                                                    <i class="fas fa-trash"></i>
                                                </a>
                                            </td>

                                        </tr>
                                    }
                                </tbody>

                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <!-- accepted payments column -->
                        <div class="col-6">
                            <p class="lead">Payment Methods:</p>
                            <img src="~/adminlte/dist/img/credit/visa.png" alt="Visa">
                            <img src="~/adminlte/dist/img/credit/mastercard.png" alt="Mastercard">
                            <img src="~/adminlte/dist/img/credit/american-express.png" alt="American Express">
                            <img src="~/adminlte/dist/img/credit/paypal2.png" alt="Paypal">

                            <p class="text-muted well well-sm shadow-none" style="margin-top: 10px;">
                                Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem
                                plugg
                                dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
                            </p>
                        </div>
                        <!-- /.col -->
                        <div class="col-6">
                            <p class="lead">Amount Due 2/22/2014</p>

                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th style="width:50%">Subtotal:</th>
                                        <td>Rp.@ViewBag.SubTotal</td>
                                    </tr>
                                    <tr>
                                        <th>Tax (5%)</th>
                                        <td>@ViewBag.Tax</td>
                                    </tr>
                                    <tr>
                                        <th>Total:</th>
                                        <td>@ViewBag.Total</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                    <!-- this row will not appear when printing -->
                    <div class="row no-print">
                        <div class="col-12">
                            <a href="invoice-print.html" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                            <form asp-action="Checkout" asp-controller="Transaction" method="post" id="form-transaction">
                                <input type="hidden" value=@ViewBag.IdHeader id="IdHeader" name="IdHeader" />
                                <input type="hidden" value=@ViewBag.IdCustomer id="IdCustomer" name="IdCustomer" />
                                <input type="hidden" value=@ViewBag.CodeTransaction id="CodeTransaction" name="CodeTransaction" />
                                <input type="hidden" value=@ViewBag.IsCheckout id="IsCheckout" name="IsCheckout" />


                                <a class="btn btn-success float-right btn-checkout">
                                    <i class="far fa-credit-card"></i> Submit
                                    Payment
                                </a>
                                </form>
                                <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;">
                                    <i class="fas fa-download"></i> Generate PDF
                                </button>
</div>
                    </div>
                </div>
                <!-- /.invoice -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content bg-default">
            <div class="modal-body" id="id-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>
<script>
    $(".btn-delete").click(function () {
        alert("test")
        var id = $(this).data("id");

        $("#id-body").empty();
        $("#id-body").load('/Transaction/Delete/' + id);
        $("#modal-default").modal("show");

    })

    $(".btn-checkout").click(function () {
        alert("test")
        var dataForm = $("#form-transaction").serialize();
        $.ajax({
            url: '/Transaction/Checkout',
            dataType:'json',
            data: dataForm,
            method:'post',
            success: function (respon) {
                if (respon.status == "success") {
                    toastr.success('Thanks for your order!')

                    setTimeout(function () {
                        window.location.href ="/Home/Index";
                    }, 1000);
                }
                else {
                    toastr.error("Error : " + respon.message)
                }
            }
        })
    })

</script>