Xsismart/Xsismart/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Xsismart.Misc;
using Xsismart.Models;
using Xsismart.ViewModels;

namespace Xsismart.Controllers
{
    public class ProductController : Controller
    {
        private readonly Xsismartcontext _context;

        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(Xsismartcontext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index(String sortOrder, string currentFilter, string searchString, int? pageNumber, int? pSize)
        {
            

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentSize"] = pSize;
            ViewBag.PageSize = PaginatedList<VMProduct>.pageSizeList();


            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            //IQueryable<VMProduct> product = list.ToList().AsQueryable();

            var product = from p in _context.Products
                          join v in _context.Variants
                          on p.IdVariant equals v.IdVariant
                          join c in _context.Categories
                          on v.IdCategory equals c.IdCategory
                          // where v.IsDelete == false
                          select new VMProduct
                          {
                              IdProduct = p.IdProduct,
                              NameProduct = p.NameProduct,
                              Price = p.Price,
                              Stock = p.Stock,
                              NameVariant = v.NameVariant
                          };

            if (!String.IsNullOrEmpty(searchString))
            {
                product = product.Where(s => s.NameProduct.Contains(searchString));
                                       
            }
            switch (sortOrder)
            {
                case "name_desc":
                    product = product.OrderByDescending(s => s.NameProduct);
                    break;
                default:
                    product = product.OrderBy(s => s.NameProduct);
                    break;
            }
            int pageSize = pSize ?? 5;
            return View(await PaginatedList<VMProduct>.CreateAsync(product, pageNumber ?? 1, pageSize));


            //List<Product> listProduct = new List<Product>()
            //{
            //    new Product(){IdProduct = 1, NameProduct="Kopi Kapal Api", Price = 5000, Stock = 10 },
            //    new Product(){IdProduct = 2, NameProduct="Sari Roti Coklat", Price = 15000, Stock = 10 },
            //    new Product(){IdProduct = 3, NameProduct="Chitato", Price = 9000, Stock = 10 }
            //};

            //    ViewBag.ListProduct = listProduct;

        }

        public async Task<IActionResult> Create()
        {
            List<Category> category = new List<Category>();
            category = (from c in _context.Categories select c).ToList();
            category.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category--" });
            ViewBag.abc = category;

            List<Variant> variants = new List<Variant>();
            variants.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant--", Description = "", IdCategory = 0 });
            ViewBag.message = variants;



            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product _product)
        {
            //Product prodNew = new Product();

            Product prodNew = _product;
            if (ModelState.IsValid)
            {
                _context.Add(prodNew);
                // _context.SaveChanges();
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            List<Category> listCat = await ListCategory();
            List<Variant> variants = new List<Variant>();
            variants.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant--", Description = "", IdCategory = 0 });
            ViewBag.abc = listCat;
            ViewBag.message = variants;

            return View(_product);
        }

        public async Task<IActionResult> Detail(int Id)
        {
            VMProduct list = await (from p in _context.Products
                                    join v in _context.Variants
                                    on p.IdVariant equals v.IdVariant
                                    join c in _context.Categories
                                    on v.IdCategory equals c.IdCategory
                                    // where v.IsDelete == false
                                    select new VMProduct
                                    {
                                        IdProduct = p.IdProduct,
                                        NameProduct = p.NameProduct,
                                        Price = p.Price,
                                        Stock = p.Stock,
                                        NameVariant = v.NameVariant,
                                        NameCategory = c.NameCategory
                                    }).FirstOrDefaultAsync(a => a.IdProduct == Id);


            if (Id == 0)
            {
                return NotFound();
            }
            Product product = await _context.Products.FirstOrDefaultAsync(a => a.IdProduct == Id);

            if (product == null)
            {
                return NotFound();
            }
            return View(list);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            ViewBag.listCat = await ListCategory();
            // List<Variant> variants = new List<Variant>();
            //variants = (from c in _context.Variants select c).ToList();
            // variants.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant--", Description = "", IdCategory = 0 });


            if (Id == 0)
            {
                return NotFound();
            }
            // var product = await _context.Products.FindAsync(Id);
            VMProduct product = await dataVP(Id);

            if (product == null)
            {
                return NotFound();
            }

            ViewBag.listVar = await DataVariant(product.IdCategory);
            return View(product);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMProduct _product)
        {
            //Product prodNew = new Product();


            if (ModelState.IsValid)
            {
                Product prod = new Product();
                prod.NameProduct = _product.NameProduct;
                prod.Price = _product.Price;
                prod.Stock = _product.Stock;
                prod.IdVariant = _product.IdVariant;

                _context.Update(_product);
                // _context.SaveChanges();
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            List<Category> listCat = await ListCategory();
            ViewBag.listCat = listCat;
            ViewBag.listVar = await DataVariant(_product.IdCategory);

            return View(_product);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.IdProduct == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExist(int id)
        {
            return _context.Products.Any(e => e.IdProduct == id);
        }

        public async Task<List<Variant>> DataVariant(int IdCategory)
        {
            List<Variant> list = await _context.Variants.
                            Where(a => a.IsDelete == false && a.IdCategory.Equals(IdCategory)).ToListAsync();
            list.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant Name--" });
            return list;
        }

        public async Task<List<Category>> ListCategory()
        {
            List<Category> category = await (from c in _context.Categories select c).ToListAsync();
            category.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category--" });
            return category;
        }

        public async Task<JsonResult> GetDataVariantAjax(int IdCategory)
        {
            List<Variant> list = await DataVariant(IdCategory);
            return Json(list);
        }

        public async Task<VMProduct> dataVP(int Id)
        {
            VMProduct list = await (from p in _context.Products
                                    join v in _context.Variants
                                    on p.IdVariant equals v.IdVariant
                                    join c in _context.Categories

Xsismart/Xsismart/Controllers/VariantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Xsismart.Models;
using Xsismart.ViewModels;

namespace Xsismart.Controllers
{
    public class VariantsController : Controller
    {
        private readonly Xsismartcontext _context;

        public VariantsController(Xsismartcontext context)
        {
            _context = context;
        }

        // GET: Variants
        public async Task<IActionResult> Index()
        {
            List<VMVariants> list = await (from v in _context.Variants
                                           join c in _context.Categories
                                           on v.IdCategory equals c.IdCategory
                                           where v.IsDelete == false
                                           select new VMVariants
                                           {
                                               IdVariant = v.IdVariant,
                                               NameVariant = v.NameVariant,
                                               Description = v.Description,
                                               NameCategory = c.NameCategory
                                           }).ToListAsync();
                                               
            return View(list);
        }

        // GET: Variants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            VMVariants list = await (from v in _context.Variants
                                           join c in _context.Categories
                                           on v.IdCategory equals c.IdCategory
                                           where v.IsDelete == false
                                           select new VMVariants
                                           {
                                               IdVariant = v.IdVariant,
                                               NameVariant = v.NameVariant,
                                               Description = v.Description,
                                               NameCategory = c.NameCategory
                                           }).FirstOrDefaultAsync(m => m.IdVariant == id);

            if (id == null)
            {
                return NotFound();
            }

            var variant = await _context.Variants
                .FirstOrDefaultAsync(m => m.IdVariant == id);
            if (variant == null)
            {
                return NotFound();
            }

            return View(list);
        }

        // GET: Variants/Create
        public async Task <IActionResult> Create()
        {
            await DropDown();
            return View();
        }

        // POST: Variants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVariant,NameVariant,Description,IsDelete,IdCategory")] Variant variant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(variant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(variant);
        }

        // GET: Variants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            List<Category> variants = new List<Category>();
            variants = (from v in _context.Categories select v).ToList();
            variants.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category--", Description = "" });
            ViewBag.message = variants;
            

            if (id == null)
            {
                return NotFound();
            }

            var variant = await _context.Variants.FindAsync(id);
            if (variant == null)
            {
                return NotFound();
            }


            return View(variant);
        }

        // POST: Variants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdVariant,NameVariant,Description,IsDelete,IdCategory")] Variant variant)
        {
            if (id != variant.IdVariant)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(variant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VariantExists(variant.IdVariant))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(variant);
        }

        // GET: Variants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var variant = await _context.Variants
                .FirstOrDefaultAsync(m => m.IdVariant == id);
            if (variant == null)
            {
                return NotFound();
            }

            return View(variant);
        }

        // POST: Variants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, [Bind("IdVariant,NameVariant,Description,IsDelete,IdCategory")] Variant variant)
        {
            if (id != variant.IdVariant)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(variant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VariantExists(variant.IdVariant))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(variant);
        }

        private bool VariantExists(int id)
        {
            return _context.Variants.Any(e => e.IdVariant == id);
        }

        public async Task<List<Category>> DropDown()
        {
            List<Category> cat = await (from c in _context.Categories select c).ToListAsync();
            cat.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category Name--" });
            ViewBag.message = cat;
            return cat;
        }
    }
}

Xsismart/Xsismart/Views/Shared/_Header.cshtml
 <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-action="Index" asp-controller="Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" asp-action="Invoice" asp-controller="Transaction" >
                <i class="fas fa-cart-plus"></i>
                <span class="badge badge-danger navbar-badge">@ViewBag.count</span>
            </a>
           
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-action="LogOut" asp-controller="Login">
                <i class="fas fa-sign-out-alt"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

Xsismart/Xsismart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @*<meta charset="utf-8" />*@
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Xsismart</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />*@
    <!-- jQuery -->
    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- Toastr -->
    <link rel="stylesheet" href="~/adminlte/plugins/toastr/toastr.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="~/adminlte/plugins/toastr/toastr.min.css">
    <!-- Toastr -->
    <script src="~/adminlte/plugins/toastr/toastr.min.js"></script>
    <!-- jQuery Validation -->
    <script src="~/adminlte/plugins/jquery-validation/jquery.validate.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/adminlte/plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/adminlte/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/adminlte/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/adminlte/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <partial name="_Header" />
        <partial name="_Sidebar" />

        <div class="content-wrapper">
            <section class="content">
                <div class="container-fluid">
                    <div class="row">

                        @RenderBody()

                    </div>
                </div>
            </section>

        </div>

        @*<div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>*@

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Xsismart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

    </div>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@

        @*@RenderSection("Scripts", required: false)*@




   
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/adminlte/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/adminlte/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/adminlte/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/adminlte/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/adminlte/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/adminlte/plugins/moment/moment.min.js"></script>
    <script src="~/adminlte/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/adminlte/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/adminlte/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/adminlte/dist/js/pages/dashboard.js"></script>
</body>
</html>

Xsismart/Xsismart/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNetCore.Http;
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/adminlte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/adminlte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">@Context.Session.GetString("customername")</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Master
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Product" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Product</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Category</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Variants" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Variant</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>